# Generated by Django 3.1.7 on 2021-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0023_auto_20210502_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pts',
            name='jenis_pts',
            field=models.CharField(choices=[('Akademi Komunitas', 'Akademi Komunitas'), ('Akademi', 'Akademi'), ('Politeknik', 'Politeknik'), ('Sekolah Tinggi', 'Sekolah Tinggi'), ('Institut', 'Institut'), ('Universitas', 'Universitas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='category',
            field=models.CharField(choices=[('SK Pendirian', 'SK Pendirian'), ('SK Perubahan', 'SK Perubahan'), ('SK Penutupan', 'SK Penutupan'), ('SK Pembukaan', 'SK Pembukaan'), ('SK Penyesuaian Nomenklatur', 'SK Penyesuaian Nomenklatur'), ('Akta Pendirian', 'Akta Pendirian'), ('Akta Perubahan', 'Akta Perubahan'), ('SK Menkumham', 'SK Menkumham'), ('SK Menkumham Pencatatan', 'SK Menkumham Pencatatan'), ('Rekomendasi', 'Rekomendasi'), ('Rekomendasi Akreditasi', 'Rekomendasi Akreditasi'), ('Surat Permohonan', 'Surat Permohonan'), ('Berita Acara', 'Berita Acara')], max_length=200, null=True),
        ),
    ]
