# Generated by Django 3.1.7 on 2021-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0025_auto_20210725_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='dokumen_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Unggah File'),
        ),
    ]
