# Generated by Django 3.1.7 on 2021-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikept', '0026_dokumen_dokumen_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='dokumen_file',
            field=models.FileField(blank=True, null=True, upload_to='media/file/', verbose_name='Unggah File'),
        ),
    ]
